##################### 获取文章列表 #################################
GET {{baseUrl}}{{basePath}}/article/all_articles
Accept: application/json

###
GET {{baseUrl}}{{basePath}}/article/all_articles/page/10/1
Accept: application/json

###
##################################################################

###################### 根据分类获取文章列表 #########################
GET {{baseUrl}}{{basePath}}/article/all_article_by_category/{{testCategoryId}}
Accept: application/json

###
GET {{baseUrl}}{{basePath}}/article/all_article_by_category/page/{{testCategoryId}}/10/1
Accept: application/json

###
##################################################################

######################## 根据用户获取文章列表 #######################
GET {{baseUrl}}{{basePath}}/article/all_article_by_user/{{testUserId}}
Accept: application/json

###
GET {{baseUrl}}{{basePath}}/article/all_article_by_user/page/{{testUserId}}/10/1
Accept: application/json

###
##################################################################

######################## 文章操作 #################################
GET {{baseUrl}}{{basePath}}/article/{{testArticleId}}
Accept: application/json

###
POST {{baseUrl}}{{basePath}}/article
Accept: application/json
authorization: {{testToken}}

     {
        "category_id": "{{testCategoryId}}",
        "article_title": "testtesttesttesttesttest",
        "article_cover": "文章封面",
        "article_describe": "sdfgsdfewrwqttrytzvcvcv",
        "article_content": "asdasdsdfsdfsdfgafdsgdsfgsdfgsdfgsdfgsdfgdfgsdfg"
    }

###
PUT {{baseUrl}}{{basePath}}/article/{{testArticleId}}
Accept: application/json
authorization: {{testToken}}

     {
        "category_id": "1",
        "article_title": "测试修改文章",
        "article_cover": "封面地址",
        "article_describe": "博客简介",
        "article_content": "博客内容，测试测试测试测试测试测试测试测试测试测试测试"
    }

###
DELETE {{baseUrl}}{{basePath}}/article/{{testArticleId}}
Accept: application/json
authorization: {{testToken}}

###
################################################################

########################## 移动文章 #############################
PATCH {{baseUrl}}{{basePath}}/article/{{testArticleId}}/move_to/user/7bea8042-8811-4bc0-a86f-0e8bcf0c2a2e
Accept: application/json
authorization: {{testToken}}

###
PATCH {{baseUrl}}{{basePath}}/article/{{testArticleId}}/move_to/category/a3d94539-c661-45e3-ba43-6deddcf5d0c9
Accept: application/json
authorization: {{testToken}}

###
################################################################